package: d2u_references
version: '1.0.8'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_references

page:
    title: 'translate:d2u_references'
    perm: d2u_references[]
    icon: rex-icon fa-thumbs-o-up
    subpages:
        reference: { title: 'translate:d2u_references_references', icon: rex-icon fa-thumbs-o-up }
        tag: { title: 'translate:d2u_references_tags', icon: rex-icon fa-tags }
        setup: { title: 'translate:d2u_references_setup', icon: rex-icon rex-icon-install, itemclass: pull-right, perm: d2u_references[settings] }
        settings: { title: 'translate:d2u_references_settings', icon: rex-icon rex-icon-system, itemclass: pull-right, perm: d2u_references[settings] }

requires:
    redaxo: >=5.10.0
    packages:
        d2u_helper: '>=1.6.2'
        sprog: '>=1.0.0'
        url: '>=1.0.1'
        yrewrite: '>=2.0.1'